// <auto-generated />
using System;
using KutuphaneAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112174608_KitaplariGuncelle")]
    partial class KitaplariGuncelle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KutuphaneAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Ömer Seyfettin"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Sabahattin Ali"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Yaşar Kemal"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Orhan Pamuk"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Reşat Nuri Güntekin"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Halide Edib Adıvar"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Zülfü Livaneli"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Fyodor Dostoyevski"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Franz Kafka"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Albert Camus"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "Stefan Zweig"
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            Name = "Victor Hugo"
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            Name = "Lev Tolstoy"
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            Name = "Gabriel Garcia Marquez"
                        });
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "978001",
                            IsDeleted = false,
                            Title = "Kaşağı"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            ISBN = "978002",
                            IsDeleted = false,
                            Title = "Falaka"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            ISBN = "978003",
                            IsDeleted = false,
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            ISBN = "978004",
                            IsDeleted = false,
                            Title = "Kuyucaklı Yusuf"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            ISBN = "978005",
                            IsDeleted = false,
                            Title = "İnce Memed"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            ISBN = "978006",
                            IsDeleted = false,
                            Title = "Yılanı Öldürseler"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            ISBN = "978007",
                            IsDeleted = false,
                            Title = "Kara Kitap"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            ISBN = "978008",
                            IsDeleted = false,
                            Title = "Masumiyet Müzesi"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            ISBN = "978009",
                            IsDeleted = false,
                            Title = "Çalıkuşu"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            ISBN = "978010",
                            IsDeleted = false,
                            Title = "Yaprak Dökümü"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            ISBN = "978011",
                            IsDeleted = false,
                            Title = "Sinekli Bakkal"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            ISBN = "978012",
                            IsDeleted = false,
                            Title = "Ateşten Gömlek"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            ISBN = "978013",
                            IsDeleted = false,
                            Title = "Serenad"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 7,
                            ISBN = "978014",
                            IsDeleted = false,
                            Title = "Kardeşimin Hikayesi"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            ISBN = "978015",
                            IsDeleted = false,
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 8,
                            ISBN = "978016",
                            IsDeleted = false,
                            Title = "Yeraltından Notlar"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            ISBN = "978017",
                            IsDeleted = false,
                            Title = "Dönüşüm"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            ISBN = "978018",
                            IsDeleted = false,
                            Title = "Dava"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 10,
                            ISBN = "978019",
                            IsDeleted = false,
                            Title = "Yabancı"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            ISBN = "978020",
                            IsDeleted = false,
                            Title = "Veba"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 11,
                            ISBN = "978021",
                            IsDeleted = false,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 11,
                            ISBN = "978022",
                            IsDeleted = false,
                            Title = "Hayvan Çiftliği"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 12,
                            ISBN = "978023",
                            IsDeleted = false,
                            Title = "Satranç"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 12,
                            ISBN = "978024",
                            IsDeleted = false,
                            Title = "Bilinmeyen Bir Kadının Mektubu"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 13,
                            ISBN = "978025",
                            IsDeleted = false,
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 13,
                            ISBN = "978026",
                            IsDeleted = false,
                            Title = "Notre Dame'ın Kamburu"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 14,
                            ISBN = "978027",
                            IsDeleted = false,
                            Title = "Savaş ve Barış"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 14,
                            ISBN = "978028",
                            IsDeleted = false,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 15,
                            ISBN = "978029",
                            IsDeleted = false,
                            Title = "Yüzyıllık Yalnızlık"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 15,
                            ISBN = "978030",
                            IsDeleted = false,
                            Title = "Kırmızı Pazartesi"
                        });
                });

            modelBuilder.Entity("KutuphaneAPI.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Merkez",
                            Email = "admin@kutuphane.com",
                            IsDeleted = false,
                            LastName = "Sistem",
                            Name = "Admin",
                            Password = "admin1905",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Book", b =>
                {
                    b.HasOne("KutuphaneAPI.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.BorrowRecord", b =>
                {
                    b.HasOne("KutuphaneAPI.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
