// <auto-generated />
using System;
using KutuphaneAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112172813_SonVeKesinCozum")]
    partial class SonVeKesinCozum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KutuphaneAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Yazar 1"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Yazar 2"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Yazar 3"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Yazar 4"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Yazar 5"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Yazar 6"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Yazar 7"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Yazar 8"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Yazar 9"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Yazar 10"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Yazar 11"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "Yazar 12"
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            Name = "Yazar 13"
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            Name = "Yazar 14"
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            Name = "Yazar 15"
                        });
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "ISBN-1A",
                            IsDeleted = false,
                            Title = "Kitap 1A"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            ISBN = "ISBN-1B",
                            IsDeleted = false,
                            Title = "Kitap 1B"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            ISBN = "ISBN-2A",
                            IsDeleted = false,
                            Title = "Kitap 2A"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            ISBN = "ISBN-2B",
                            IsDeleted = false,
                            Title = "Kitap 2B"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            ISBN = "ISBN-3A",
                            IsDeleted = false,
                            Title = "Kitap 3A"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            ISBN = "ISBN-3B",
                            IsDeleted = false,
                            Title = "Kitap 3B"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            ISBN = "ISBN-4A",
                            IsDeleted = false,
                            Title = "Kitap 4A"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            ISBN = "ISBN-4B",
                            IsDeleted = false,
                            Title = "Kitap 4B"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            ISBN = "ISBN-5A",
                            IsDeleted = false,
                            Title = "Kitap 5A"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            ISBN = "ISBN-5B",
                            IsDeleted = false,
                            Title = "Kitap 5B"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            ISBN = "ISBN-6A",
                            IsDeleted = false,
                            Title = "Kitap 6A"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            ISBN = "ISBN-6B",
                            IsDeleted = false,
                            Title = "Kitap 6B"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            ISBN = "ISBN-7A",
                            IsDeleted = false,
                            Title = "Kitap 7A"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 7,
                            ISBN = "ISBN-7B",
                            IsDeleted = false,
                            Title = "Kitap 7B"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            ISBN = "ISBN-8A",
                            IsDeleted = false,
                            Title = "Kitap 8A"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 8,
                            ISBN = "ISBN-8B",
                            IsDeleted = false,
                            Title = "Kitap 8B"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            ISBN = "ISBN-9A",
                            IsDeleted = false,
                            Title = "Kitap 9A"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            ISBN = "ISBN-9B",
                            IsDeleted = false,
                            Title = "Kitap 9B"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 10,
                            ISBN = "ISBN-10A",
                            IsDeleted = false,
                            Title = "Kitap 10A"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            ISBN = "ISBN-10B",
                            IsDeleted = false,
                            Title = "Kitap 10B"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 11,
                            ISBN = "ISBN-11A",
                            IsDeleted = false,
                            Title = "Kitap 11A"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 11,
                            ISBN = "ISBN-11B",
                            IsDeleted = false,
                            Title = "Kitap 11B"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 12,
                            ISBN = "ISBN-12A",
                            IsDeleted = false,
                            Title = "Kitap 12A"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 12,
                            ISBN = "ISBN-12B",
                            IsDeleted = false,
                            Title = "Kitap 12B"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 13,
                            ISBN = "ISBN-13A",
                            IsDeleted = false,
                            Title = "Kitap 13A"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 13,
                            ISBN = "ISBN-13B",
                            IsDeleted = false,
                            Title = "Kitap 13B"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 14,
                            ISBN = "ISBN-14A",
                            IsDeleted = false,
                            Title = "Kitap 14A"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 14,
                            ISBN = "ISBN-14B",
                            IsDeleted = false,
                            Title = "Kitap 14B"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 15,
                            ISBN = "ISBN-15A",
                            IsDeleted = false,
                            Title = "Kitap 15A"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 15,
                            ISBN = "ISBN-15B",
                            IsDeleted = false,
                            Title = "Kitap 15B"
                        });
                });

            modelBuilder.Entity("KutuphaneAPI.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Merkez",
                            Email = "admin@kutuphane.com",
                            IsDeleted = false,
                            LastName = "Sistem",
                            Name = "Admin",
                            Password = "admin1905",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Book", b =>
                {
                    b.HasOne("KutuphaneAPI.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.BorrowRecord", b =>
                {
                    b.HasOne("KutuphaneAPI.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KutuphaneAPI.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
